### PR TITLE
Add support for C7 family instances.

### PR DESCRIPTION
**Pull request by mwvaughn**
Some AWS Regions have C7 instances deployed. This change adds support for those.

## PR Quality Checklist

- [ ] I added tests to new or existing code
- [ ] I removed hardcoded strings and used [`react-i18next`](https://react.i18next.com/) library ([useTranslation hook](https://react.i18next.com/latest/usetranslation-hook) and/or [Trans component](https://react.i18next.com/latest/trans-component)), see an example [here](https://github.com/aws/aws-parallelcluster-ui/commit/a6f1e2aa46b245b5bf7500a04b83195477a5cfa5)
- [ ] I made sure no sensitive info gets logged at any time in the codebase (see [here](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)) (e.g. no user info or details, no stacktraces, etc.)
- [ ] I checked that infrastructure/update_infrastructure.sh runs without any error
- [x] I checked that `npm run build` builds without any error
- [x] I checked that clusters are listed correctly
- [x] I checked that a new cluster can be created (config is produced and dry run passes)
- [x] I checked that login and logout work as expected

In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the [Project Guidelines](../PROJECT_GUIDELINES.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mtfranchetto** [comment]
Thanks @mwvaughn! Just to be sure, have you tested this change in your local environment?

**Comment by mwvaughn** [comment]
Yes. Here's documentary evidence from my local env this morning. 

CleanShot 2023-03-07 at 08 48 25@2x

**Comment by mwvaughn** [comment]
Yes, confirmed as working. Here is documentary evidence from my local env this morning. 

CleanShot 2023-03-07 at 08 50 40@2x

**Comment by mtfranchetto** [comment]
Perfect, merging!

**Review by mtfranchetto — APPROVED** [review]

**Pull request merged**
